# Generated by Django 6.0.1 on 2026-02-03 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0002_mainmodel_testmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='main',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='promocode.mainmodel'),
        ),
    ]
