# Generated by Django 6.0.1 on 2026-02-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0003_testmodel_main'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainmodel',
            options={'verbose_name': 'Main Model', 'verbose_name_plural': 'Main Model'},
        ),
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name': 'Promocode', 'verbose_name_plural': 'Promocodes'},
        ),
        migrations.AlterModelOptions(
            name='testmodel',
            options={'verbose_name': 'Test Model', 'verbose_name_plural': 'Test Model'},
        ),
        migrations.AddField(
            model_name='mainmodel',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='mainmodel',
            name='created_at',
            field=models.DateField(verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='mainmodel',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='mainmodel',
            name='updated_at',
            field=models.DateField(verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='description',
            field=models.CharField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='promocode',
            field=models.CharField(max_length=100, verbose_name='Promocode'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='file',
            field=models.FileField(upload_to='', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='number',
            field=models.IntegerField(verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
    ]
