# Generated by Django 6.0.1 on 2026-02-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0004_alter_mainmodel_options_alter_promocode_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmodel',
            name='created_at',
            field=models.DateField(blank=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='mainmodel',
            name='updated_at',
            field=models.DateField(blank=True, null=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
    ]
