# Generated by Django 6.0.1 on 2026-02-04 13:59

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0006_listmodel_mainmodel_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='main',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='promocode.mainmodel'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Text'),
        ),
    ]
